# Generated by Django 2.2.11 on 2020-03-10 17:41

from django.db import migrations, models

# this field used to use an external library called django-timezone-field it uses a charfield, it
# didn't work, we got rid of it, this (should) now be manually patched out.  That field type
# should just be a CharField with a max_length of 63.  The default value was 'America/New_York'.

class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_auto_20200310_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='timezone',
            field=models.CharField(default='America/New_York', help_text='Timezone of the study', max_length=63),
        ),
    ]
