# Generated by Django 2.2.15 on 2021-03-09 21:45

from django.db import migrations, models
import django.db.models.deletion


def seed_forest_metadata(apps, schema_editor):
    """
    Seed initial default ForestMetadata objects
    """
    db_alias = schema_editor.connection.alias
    ForestMetadata = apps.get_model("database", "ForestMetadata")
    ForestMetadata.objects.using(db_alias).create()  # Fill me in


def seed_study_forest_metadata(apps, schema_editor):
    """
    Associate existing Study objects with the default ForestMetadata.
    """
    pass  # Fill me in


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0050_auto_20210226_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('default', models.NullBooleanField(unique=True)),
                ('notes', models.TextField(blank=True)),
                ('name', models.TextField(blank=True)),
                ('jasmine_json_string', models.TextField()),
                ('willow_json_string', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(seed_forest_metadata, migrations.RunPython.noop),
        migrations.AddField(
            model_name='study',
            name='forest_metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='database.ForestMetadata'),
        ),
        migrations.RunPython(seed_study_forest_metadata, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='study',
            name='forest_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.ForestMetadata'),
        ),
        # migrations.AddField(
        #     model_name='study',
        #     name='forest_metadata',
        #     # Note: this will fail if we ever need to use the default
        #     field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='database.ForestMetadata'),
        #     preserve_default=False,
        # ),
        migrations.RemoveField(
            model_name='foresttracker',
            name='metadata_hash',
        ),
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='study',
        ),
        migrations.AddField(
            model_name='foresttracker',
            name='process_download_end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foresttracker',
            name='forest_tree',
            field=models.TextField(choices=[('jasmine', 'jasmine'), ('willow', 'willow')]),
        ),
        migrations.AlterField(
            model_name='foresttracker',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.ForestMetadata'),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='jasmine_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jasmine_summary_statistics', to='database.ForestMetadata'),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='willow_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='willow_summary_statistics', to='database.ForestMetadata'),
        ),
    ]
