# Generated by Django 2.2.19 on 2021-03-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0051_auto_20210325_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foresttracker',
            name='commit_hash',
        ),
        migrations.RemoveField(
            model_name='foresttracker',
            name='file_size',
        ),
        migrations.AddField(
            model_name='foresttracker',
            name='total_file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foresttracker',
            name='forest_version',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
