# Generated by Django 4.2.15 on 2024-09-24 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('database', '0127_study_end_date_study_manually_stopped'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='omniring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='omniring_global_offset_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='omniring_on_duration_seconds',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='omniring_total_duration_seconds',
            field=models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
