# Generated by Django 4.2.15 on 2024-11-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0128_devicesettings_omniring_and_more'),
        ('database', '0132_participant_last_known_surveys_available_and_more'),
    ]

    operations = [
    ]
