# Generated by Django 4.2.15 on 2024-11-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0132_participant_last_known_surveys_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedevent',
            name='was_resend',
            field=models.BooleanField(default=False),
        ),
    ]
