# Generated by Django 4.2.15 on 2024-12-16 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0133_archivedevent_was_resend'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='resend_period_minutes',
            field=models.PositiveIntegerField(default=180, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
