# Generated by Django 4.2.15 on 2024-12-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0134_devicesettings_resend_period_minutes'),
    ]

    operations = [
        # the original field was somewhat incorrect due to a release timing issue, any servers
        # running an older version have to be migrated manually to preserve correct time, but that
        # should just be our staging server.
        migrations.RemoveField(
            model_name='globalsettings',
            name='earliest_possible_time_of_push_notification_resend',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='push_notification_resend_enabled',
            field=models.DateTimeField(default=None, null=True, blank=True),
        ),
    ]
