# Generated by Django 4.2.15 on 2025-01-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0135_remove_globalsettings_earliest_possible_time_of_push_notification_resend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='no_resend',
            field=models.BooleanField(default=False),
        ),
    ]
