# Generated by Django 4.2.20 on 2025-05-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0137_s3file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='jasmine_gps_data_missing_duration',
        ),
    ]
