# Generated by Django 4.2.21 on 2025-05-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0138_remove_summarystatisticdaily_jasmine_gps_data_missing_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineEncryptionError',
        ),
    ]
