# Generated by Django 5.2.2 on 2025-06-13 08:20

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


# from django.contrib.postgres.indexes

class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('database', '0139_delete_lineencryptionerror'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='s3file',
            index=models.Index(fields=['created_on'], name='s3file_created_on_idx'),
        ),
    ]
