# Generated by Django 5.2.2 on 2025-06-13 09:18

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('database', '0140_alter_s3file_created_on'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='s3file',
            index=models.Index(fields=['sha1'], name='s3file_sha1_idx'),
        ),
    ]
