# Generated by Django 5.2.2 on 2025-06-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0141_add_s3file_index_sha1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s3file',
            name='compression_time_ns',
        ),
        migrations.RemoveField(
            model_name='s3file',
            name='decompression_time_ns',
        ),
        migrations.RemoveField(
            model_name='s3file',
            name='decrypt_time_ns',
        ),
        migrations.RemoveField(
            model_name='s3file',
            name='download_time_ns',
        ),
        migrations.RemoveField(
            model_name='s3file',
            name='encryption_time_ns',
        ),
        migrations.RemoveField(
            model_name='s3file',
            name='upload_time_ns',
        ),
        migrations.AddField(
            model_name='s3file',
            name='glacier',
            field=models.BooleanField(default=False),
        ),
    ]
