# Generated by Django 5.2.4 on 2025-08-21 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0142_remove_s3file_compression_time_ns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='bad_login_attempts',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='researcher',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
