# Generated by Django 5.2.6 on 2025-09-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0143_researcher_bad_login_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProcessingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
