# Generated by Django 5.2.7 on 2025-10-14 09:18, modified by Eli Jones

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.state import StateApps
from collections import defaultdict


# turns out instantiating those is too slow
# def fill_study_id(apps: StateApps, schema_editor):
#     ForestTask = apps.get_model('database', 'ForestTask')
#     SummaryStatisticDaily = apps.get_model('database', 'SummaryStatisticDaily')
#     Participant = apps.get_model('database', 'Participant')
#
#     study_lookup = dict(Participant.objects.values_list("id", "study_id"))
#
#     updates_summaries = []
#
#     for summary_id, participant_id in SummaryStatisticDaily.objects.values_list("id", "participant_id"):
#         updates_summaries.append(SummaryStatisticDaily(pk=summary_id, the_study_id=study_lookup[participant_id]))
#         if len(updates_summaries) >= 1000:
#             SummaryStatisticDaily.objects.bulk_update(updates_summaries, ["the_study_id"])
#             print(f"Updated {len(updates_summaries)} SummaryStatisticDaily records")
#             updates_summaries = []
#     SummaryStatisticDaily.objects.bulk_update(updates_summaries, ["the_study_id"])
#     print(f"Updated {len(updates_summaries)} SummaryStatisticDaily records")
#
#     forest_task_updates = []
#     for task_id, participant_id in ForestTask.objects.values_list("id", "participant_id"):
#         forest_task_updates.append(ForestTask(pk=task_id, the_study_id=study_lookup[participant_id]))
#         if len(forest_task_updates) >= 1000:
#             ForestTask.objects.bulk_update(forest_task_updates, ["the_study_id"])
#             print(f"Updated {len(forest_task_updates)} ForestTask records")
#             forest_task_updates = []
#     ForestTask.objects.bulk_update(forest_task_updates, ["the_study_id"])
#     print(f"Updated {len(forest_task_updates)} ForestTask records")


# much much much faster
def fill_study_id(apps: StateApps, schema_editor):
    Participant = apps.get_model('database', 'Participant')
    SummaryStatisticDaily = apps.get_model('database', 'SummaryStatisticDaily')
    ForestTask = apps.get_model('database', 'ForestTask')
    
    participants_by_study = defaultdict(list)
    for p_pk, s_pk in Participant.objects.values_list("pk", "study_id"):
        participants_by_study[s_pk].append(p_pk)
    participants_by_study = dict(participants_by_study)
    
    for s_pk, p_pks in participants_by_study.items():
        SummaryStatisticDaily.objects.filter(participant_id__in=p_pks).update(the_study_id=s_pk)
        ForestTask.objects.filter(participant_id__in=p_pks).update(the_study_id=s_pk)
        print(f"Updated ForestTask and SummaryStatisticDaily for Study {s_pk}")
    
    # this is actually slower
    # Study = apps.get_model('database', 'Study')
    # for study_id in Study.objects.values_list("id", flat=True):
    #     SummaryStatisticDaily.objects.filter(participant__study_id=study_id).update(the_study_id=study_id)
    #     ForestTask.objects.filter(participant__study_id=study_id).update(the_study_id=study_id)
    #     print(f"Updated ForestTask and SummaryStatisticDaily for Study {study_id}")


class Migration(migrations.Migration):
    
    dependencies = [
        ('database', '0144_dataprocessingstatus'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='foresttask',
            name='the_study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='database.study'),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='the_study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='database.study'),
        ),
        migrations.RunPython(fill_study_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='foresttask',
            name='the_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.study', related_name='forest_tasks'),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='the_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.study', related_name='summary_statistics_daily'), 
        ),
    ]
