# Generated by Django 5.2.7 on 2025-10-14 09:18, modified by Eli Jones

from typing import TYPE_CHECKING
from django.db.migrations.state import StateApps
import django.db.models.deletion
from django.db import migrations, models


if TYPE_CHECKING:
    from database.models import ForestTask as _ForestTask
    from database.models import SummaryStatisticDaily as _SummaryStatisticDaily
    from database.models import Participant as _Participant


def fill_study_id(apps: StateApps, schema_editor):
    ForestTask: _ForestTask = apps.get_model('database', 'ForestTask')
    SummaryStatisticDaily: _SummaryStatisticDaily = apps.get_model('database', 'SummaryStatisticDaily')
    Participant: _Participant = apps.get_model('database', 'Participant')
    
    study_lookup = dict(Participant.objects.values_list("id", "study_id"))
    
    updates_summaries = []
    
    for summary_id, participant_id in SummaryStatisticDaily.objects.values_list("id", "participant_id"):
        updates_summaries.append(SummaryStatisticDaily(pk=summary_id, the_study_id=study_lookup[participant_id]))
    
    forest_task_updates = []
    for task_id, participant_id in ForestTask.objects.values_list("id", "participant_id"):
        forest_task_updates.append(ForestTask(pk=task_id, the_study_id=study_lookup[participant_id]))
    
    SummaryStatisticDaily.objects.bulk_update(updates_summaries, ["the_study_id"])
    ForestTask.objects.bulk_update(forest_task_updates, ["the_study_id"])


class Migration(migrations.Migration):
    
    dependencies = [
        ('database', '0144_dataprocessingstatus'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='foresttask',
            name='the_study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='database.study'),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='the_study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='database.study'),
        ),
        migrations.RunPython(fill_study_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='foresttask',
            name='the_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.study', related_name='forest_tasks'),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='the_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.study', related_name='summary_statistics_daily'), 
        ),
    ]
