# Generated by Django 5.2.8 on 2025-12-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0145_foresttask_study_summarystatisticdaily_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveynotificationreport',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
