# Generated by Django 5.2.8 on 2026-01-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0146_alter_surveynotificationreport_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='first_push_notification_checkin',
        ),
    ]
