# Generated by Django 5.2.10 and manually edited on 2026-02-06 18:35

from django.db import migrations
from django.db.migrations.state import StateApps


def clear_ios_decryption_key_events(apps: StateApps, schema_editor):
    # purge any leftover events from the entire ios decryption key saga...
    GenericEvent = apps.get_model('database', 'GenericEvent')
    tag = "problem_upload_file_IosDecryptionKeyNotFoundError"
    GenericEvent.objects.filter(tag=tag).delete()


class Migration(migrations.Migration):
    
    dependencies = [
        ('database', '0147_remove_participant_first_push_notification_checkin'),
    ]
    
    operations = [
        migrations.DeleteModel(
            name='IOSDecryptionKey',
        ),
        migrations.RunPython(clear_ios_decryption_key_events, migrations.RunPython.noop)
    ]
