# Generated by Django 5.2.11 on 2026-05-05 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0148_delete_iosdecryptionkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='sycamore_average_duration',
        ),
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='sycamore_average_time_to_open',
        ),
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='sycamore_average_time_to_submit',
        ),
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='sycamore_task',
        ),
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='sycamore_total_completed_surveys',
        ),
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='sycamore_total_opened_surveys',
        ),
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='sycamore_total_surveys',
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='willow_call_reciprocity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='willow_mean_responsiveness_call',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foresttask',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='database.participant'),
        ),
        migrations.CreateModel(
            name='SycamoreAnalysisOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('obs_duration', models.FloatField(null=True)),
                ('obs_day', models.FloatField(null=True)),
                ('obs_night', models.FloatField(null=True)),
                ('home_duration', models.FloatField(null=True)),
                ('distance_traveled', models.FloatField(null=True)),
                ('distance_from_home', models.FloatField(null=True)),
                ('gyration_radius', models.FloatField(null=True)),
                ('distance_diameter', models.FloatField(null=True)),
                ('significant_location_count', models.FloatField(null=True)),
                ('significant_location_entropy', models.FloatField(null=True)),
                ('total_flight_time', models.FloatField(null=True)),
                ('flight_distance_average', models.FloatField(null=True)),
                ('flight_distance_stddev', models.FloatField(null=True)),
                ('flight_duration_average', models.FloatField(null=True)),
                ('flight_duration_stddev', models.FloatField(null=True)),
                ('pause_time', models.FloatField(null=True)),
                ('av_pause_duration', models.FloatField(null=True)),
                ('sd_pause_duration', models.FloatField(null=True)),
                ('physical_circadian_rhythm', models.FloatField(null=True)),
                ('physical_circadian_rhythm_stratified', models.FloatField(null=True)),
                ('forest_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sycamore_analysis_output', to='database.foresttask')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sycamore_analyses', to='database.study')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
