# Generated by Django 5.2.10 on 2026-02-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0148_delete_iosdecryptionkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('audio_survey', 'audio_survey'), ('tracking_survey', 'tracking_survey'), ('ai_chat_survey', 'ai_chat_survey')], help_text='What type of survey this is.', max_length=16),
        ),
        migrations.AlterField(
            model_name='surveyarchive',
            name='survey_type',
            field=models.CharField(choices=[('audio_survey', 'audio_survey'), ('tracking_survey', 'tracking_survey'), ('ai_chat_survey', 'ai_chat_survey')], help_text='What type of survey this is.', max_length=16),
        ),
    ]
