# Generated by Django 5.2.14 on 2026-05-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0148_delete_iosdecryptionkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='sycamore_average_duration',
        ),
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='sycamore_average_time_to_open',
        ),
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='sycamore_average_time_to_submit',
        ),
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='sycamore_task',
        ),
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='sycamore_total_completed_surveys',
        ),
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='sycamore_total_opened_surveys',
        ),
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='sycamore_total_surveys',
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='jasmine_physical_circadian_rhythm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='jasmine_physical_circadian_rhythm_stratified',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='willow_call_reciprocity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='willow_mean_responsiveness_call',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='willow_mean_responsiveness_text',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foresttask',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forest_tasks', to='database.participant'),
        ),
    ]
