# Generated by Django 5.2.10 on 2026-02-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0149_alter_survey_survey_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarystatisticdaily',
            old_name='beiwe_ambient_audio_bytes',
            new_name='beiwe_ai_chat_logs_bytes',
        ),
        migrations.RemoveField(
            model_name='devicesettings',
            name='ambient_audio',
        ),
        migrations.RemoveField(
            model_name='devicesettings',
            name='ambient_audio_bitrate',
        ),
        migrations.RemoveField(
            model_name='devicesettings',
            name='ambient_audio_off_duration_seconds',
        ),
        migrations.RemoveField(
            model_name='devicesettings',
            name='ambient_audio_on_duration_seconds',
        ),
        migrations.RemoveField(
            model_name='devicesettings',
            name='ambient_audio_sampling_rate',
        ),
    ]
