# Generated by Django 5.2.14 on 2026-07-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0149_remove_summarystatisticdaily_sycamore_average_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicesettings',
            name='ambient_audio',
        ),
        migrations.RemoveField(
            model_name='devicesettings',
            name='ambient_audio_bitrate',
        ),
        migrations.RemoveField(
            model_name='devicesettings',
            name='ambient_audio_off_duration_seconds',
        ),
        migrations.RemoveField(
            model_name='devicesettings',
            name='ambient_audio_on_duration_seconds',
        ),
        migrations.RemoveField(
            model_name='devicesettings',
            name='ambient_audio_sampling_rate',
        ),
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='beiwe_ambient_audio_bytes',
        ),
    ]
