# Generated by Django 5.2.14 on 2026-08-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0150_remove_devicesettings_ambient_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foresttask',
            name='creator',
            field=models.TextField(blank=True),
        ),
    ]
