# Generated by Django 5.2.14 on 2026-09-03 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0151_foresttask_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appheartbeats',
            name='message',
        ),
    ]
